SELECT 
     CHAMADOS_SUPORTE.IdCHSup,
	 CHAMADOS_SUPORTE.StatusCha,
	 CHAMADOS_SUPORTE.DataCha,
	 CHAMADOS_SUPORTE.AssuntoSuporte,
	 CHAMADOS_SUPORTE.TipoChamadoSuporte,
	 CHAMADOS_SUPORTE.IdUsuario,
	 CHAMADOS_SUPORTE.IdSolicitante,
	 CHAMADOS_SUPORTE.IdAtendente,
	 ITENS_CHAMADOS_SUPORTE.IdSoftware,
	 ITENS_CHAMADOS_SUPORTE.IdModulo,
	 ITENS_CHAMADOS_SUPORTE.DataItemCh,
	 ITENS_CHAMADOS_SUPORTE.HorarioInicio,
	 ITENS_CHAMADOS_SUPORTE.HorarioTermino,
	 ITENS_CHAMADOS_SUPORTE.TextoSuporte,
	 ITENS_CHAMADOS_SUPORTE.TextoDesenvol
	 FROM CHAMADOS_SUPORTE
	 INNER JOIN ITENS_CHAMADOS_SUPORTE
	 ON CHAMADOS_SUPORTE.IdCHSup=ITENS_CHAMADOS_SUPORTE.IdCHSup
	 INNER USUARIOS
	 ON CHAMADOS
	 WHERE ITENS_CHAMADOS_SUPORTE.DataItemCh BETWEEN '2021/01/01'
	 AND '2021/01/31'