SELECT 
     CHAMADOS_SUPORTE.IdCHSup,
	 CHAMADOS_SUPORTE.StatusCha,
	 CHAMADOS_SUPORTE.DataCha,
	 CHAMADOS_SUPORTE.AssuntoSuporte,
	 CHAMADOS_SUPORTE.TipoChamadoSuporte,
	 CHAMADOS_SUPORTE.IdUsuario,
	 USUARIOS.NomeUsuario,
	 CHAMADOS_SUPORTE.IdSolicitante,
	 SOLICITANTES.NomeSolicitante,
	 CHAMADOS_SUPORTE.IdAtendente,
	 ATENDENTES.NomeAtendente,
	 ITENS_CHAMADOS_SUPORTE.IdSoftware,
	 SOFTWARE.DescricaoSoftware,
	 ITENS_CHAMADOS_SUPORTE.IdModulo,
	 MODULOS.DescricaoModulo,
	 ITENS_CHAMADOS_SUPORTE.DataItemCh,
	 ITENS_CHAMADOS_SUPORTE.HorarioInicio,
	 ITENS_CHAMADOS_SUPORTE.HorarioTermino,
	 ITENS_CHAMADOS_SUPORTE.TextoSuporte,
	 ITENS_CHAMADOS_SUPORTE.TextoDesenvol
	 FROM CHAMADOS_SUPORTE
	 INNER JOIN ITENS_CHAMADOS_SUPORTE
	 ON CHAMADOS_SUPORTE.IdCHSup=ITENS_CHAMADOS_SUPORTE.IdCHSup
	 INNER JOIN USUARIOS
	 ON CHAMADOS_SUPORTE.IdUsuario=USUARIOS.IdUsuario
	 INNER JOIN SOLICITANTES
	 ON CHAMADOS_SUPORTE.IdSolicitante=SOLICITANTES.IdSolicitante
	 INNER JOIN ATENDENTES
	 ON CHAMADOS_SUPORTE.IdAtendente=ATENDENTES.IdAtendente
	 INNER JOIN SOFTWARE
	 ON ITENS_CHAMADOS_SUPORTE.IdSoftware=SOFTWARE.IdSoftware
	 INNER JOIN MODULOS
	 ON ITENS_CHAMADOS_SUPORTE.IdModulo=MODULOS.IdModulo
	 WHERE ITENS_CHAMADOS_SUPORTE.DataItemCh BETWEEN '2020/01/01'
	 AND '2021/01/31'
	 AND USUARIOS.NomeUsuario='LIN WI FU'